name: Publish PowerShell Script

on:
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          $env:PSGalleryApiKey = "${{ secrets.NUGET_KEY }}"
          Publish-Script -Path ./IntuneAssignmentChecker.ps1 -Repository PSGallery -NuGetApiKey $env:PSGalleryApiKey
